lib/language_web/router.ex
defmodule LanguageWeb.Router do
  use LanguageWeb, :router

  alias LanguageWeb.Plugs.Authentication

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :authenticate do
    plug :browser
    plug Authentication, level: :user
  end

  pipeline :authenticate_admin do
    plug :authenticate
    plug Authentication, level: :admin
  end

  scope "/", LanguageWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/login", SessionController, :login
    post "/login", SessionController, :login
    get "/logout", SessionController, :logout
  end

  scope "/", LanguageWeb do
    pipe_through :authenticate 

    get "/browse", ReadController, :browse
    get "/start", ReadController, :start
  end

  scope "/", LanguageWeb do
    pipe_through :browser # :authenticate_admin

    resources "/users", UserController
  end

  scope "/vocab", LanguageWeb do
    pipe_through :authenticate

    resources "/wordlists", WordListController
    resources "/words", WordController
  end

end

lib/language/vocab/word.ex
defmodule Language.Vocab.Word do
  use Ecto.Schema
  import Ecto.Changeset

  alias Language.Vocab.WordList


  schema "words" do
    field :audio, :string
    field :native, :string
    field :notes, :string
    field :replacement, :string
    belongs_to :word_list, WordList

    timestamps()
  end

  @doc false
  def changeset(word, attrs) do
    word
    |> cast(attrs, [:native, :replacement, :notes, :audio, :word_list_id])
    |> validate_required([:native, :replacement, :word_list_id])
  end
end

lib/language_web/controllers/word_controller.ex
defmodule LanguageWeb.WordController do
  use LanguageWeb, :controller

  alias Language.Vocab
  alias Language.Vocab.Word

  def new(conn, %{"word_list" => word_list_id}) do
    changeset = Vocab.change_word(%Word{word_list_id: word_list_id})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"word" => word_params}) do
    case Vocab.create_word(word_params) do
      {:ok, word} ->
        conn
        |> put_flash(:info, "Word created successfully.")
        |> redirect(to: word_path(conn, :show, word))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    word = Vocab.get_word!(id)
    render(conn, "show.html", word: word)
  end

  def edit(conn, %{"id" => id}) do
    word = Vocab.get_word!(id)
    changeset = Vocab.change_word(word)
    render(conn, "edit.html", word: word, changeset: changeset)
  end

  def update(conn, %{"id" => id, "word" => word_params}) do
    word = Vocab.get_word!(id)

    case Vocab.update_word(word, word_params) do
      {:ok, word} ->
        conn
        |> put_flash(:info, "Word updated successfully.")
        |> redirect(to: word_path(conn, :show, word))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", word: word, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    word = Vocab.get_word!(id)
    {:ok, _word} = Vocab.delete_word(word)

    conn
    |> put_flash(:info, "Word deleted successfully.")
    |> redirect(to: word_path(conn, :index))
  end
end

lib/language_web/views/word_view.ex
defmodule LanguageWeb.WordView do
  use LanguageWeb, :view
end

lib/language_web/templates/word/edit.html.eex
<h2>Edit Word</h2>

<%= render "form.html", Map.put(assigns, :action, word_path(@conn, :update, @word)) %>

<span><%= link "Back", to: word_path(@conn, :index) %></span>

lib/language_web/templates/word/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :native, class: "control-label" %>
    <%= text_input f, :native, class: "form-control" %>
    <%= error_tag f, :native %>
  </div>

  <div class="form-group">
    <%= label f, :replacement, class: "control-label" %>
    <%= text_input f, :replacement, class: "form-control" %>
    <%= error_tag f, :replacement %>
  </div>

  <div class="form-group">
    <%= label f, :notes, class: "control-label" %>
    <%= textarea f, :notes, class: "form-control" %>
    <%= error_tag f, :notes %>
  </div>

  <div class="form-group">
    <%= label f, :audio, class: "control-label" %>
    <%= text_input f, :audio, class: "form-control" %>
    <%= error_tag f, :audio %>
  </div>

  <%= hidden_input f, :word_list_id %>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/language_web/templates/word/new.html.eex
<h2>New Word</h2>

<%= render "form.html", Map.put(assigns, :action, word_path(@conn, :create)) %>

<span><%= link "Back", to: word_path(@conn, :index) %></span>

lib/language_web/templates/word/show.html.eex
<h2>Show Word</h2>

<ul>

  <li>
    <strong>Native:</strong>
    <%= @word.native %>
  </li>

  <li>
    <strong>Replacement:</strong>
    <%= @word.replacement %>
  </li>

  <li>
    <strong>Notes:</strong>
    <%= @word.notes %>
  </li>

  <li>
    <strong>Audio:</strong>
    <%= @word.audio %>
  </li>

</ul>

<span><%= link "Edit", to: word_path(@conn, :edit, @word) %></span>
<span><%= link "Back", to: word_list_path(@conn, :index) %></span>