lib/language_web/router.ex
defmodule LanguageWeb.Router do
  use LanguageWeb, :router

  alias LanguageWeb.Plugs.Authentication

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :authenticate do
    plug :browser
    plug Authentication, level: :user
  end

  pipeline :authenticate_admin do
    plug :authenticate
    plug Authentication, level: :admin
  end

  scope "/", LanguageWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/login", SessionController, :login
    post "/login", SessionController, :login
    get "/logout", SessionController, :logout
  end

  scope "/", LanguageWeb do
    pipe_through :authenticate 

    get "/browse", ReadController, :browse
    get "/start", ReadController, :start
  end

  scope "/", LanguageWeb do
    pipe_through :browser # :authenticate_admin

    resources "/users", UserController
  end

  scope "/vocab", LanguageWeb do
    pipe_through :authenticate

    resources "/wordlists", WordListController
    resources "/words", WordController
  end

end

lib/language/vocab/word_list.ex
defmodule Language.Vocab.WordList do
  use Ecto.Schema
  import Ecto.Changeset

  alias Language.Vocab.Word

  schema "wordlists" do
    field :title, :string
    field :summary, :string
    has_many :words, Word
    belongs_to :user, Language.Accounts.User

    timestamps()
  end

  @doc false
  def changeset(word_list, attrs) do
    word_list
    |> cast(attrs, [:title, :summary, :user_id])
    |> validate_required([:title, :user_id])
  end
end

lib/language_web/controllers/word_list_controller.ex
defmodule LanguageWeb.WordListController do
  use LanguageWeb, :controller

  alias Language.Vocab
  alias Language.Vocab.WordList

  plug :authorise_wordlist when action in [:show, :edit, :update, :delete]

  defp authorise_wordlist(conn, _) do
    list = Vocab.get_word_list(conn.params["id"])
    if list == nil or list.user_id != conn.assigns[:user] do
      put_status(conn, 404)
      |> render(LanguageWeb.ErrorView, "404.html")
      |> halt()
    else
      conn
    end
  end

  def index(conn, _) do
    word_lists = Vocab.list_users_wordlists(conn.assigns[:user])
    render(conn, "index.html", word_lists: word_lists)
  end

  def new(conn, _) do
    changeset = Vocab.change_word_list(%WordList{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"word_list" => list_params}) do
    params = Enum.into(%{"user_id" => conn.assigns[:user]}, list_params)

    case Vocab.create_word_list(params) do
      {:ok, word} ->
        conn
        |> put_flash(:info, "Word list created successfully.")
        |> redirect(to: word_list_path(conn, :show, word))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    word_list = Vocab.get_word_list!(id)
    render(conn, "show.html", word_list: word_list)
  end

  def edit(conn, %{"id" => id}) do
    word_list = Vocab.get_word_list!(id)
    changeset = Vocab.change_word_list(word_list)
    render(conn, "edit.html", word_list: word_list, changeset: changeset)
  end

  def update(conn, %{"id" => id, "word_list" => word_list_params}) do
    word_list = Vocab.get_word_list!(id)
    word_list_params = Enum.into(%{"user_id" => conn.assigns[:user]}, word_list_params)

    case Vocab.update_word_list(word_list, word_list_params) do
      {:ok, word_list} ->
        conn
        |> put_flash(:info, "Word list updated successfully.")
        |> redirect(to: word_list_path(conn, :show, word_list))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", word_list: word_list, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    word_list = Vocab.get_word_list!(id)
    {:ok, _word_list} = Vocab.delete_word_list(word_list)

    conn
    |> put_flash(:info, "Word list deleted successfully.")
    |> redirect(to: word_list_path(conn, :index))
  end
end

lib/language_web/views/word_list_view.ex
defmodule LanguageWeb.WordListView do
  use LanguageWeb, :view
end

lib/language_web/templates/word_list/edit.html.eex
<h2>Edit Word List</h2>

<%= render "form.html", Map.put(assigns, :action, word_list_path(@conn, :update, @word_list)) %>

<span><%= link "Back", to: word_list_path(@conn, :index) %></span>

lib/language_web/templates/word_list/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= label f, :summary, class: "control-label" %>
    <%= text_input f, :summary, class: "form-control" %>
    <%= error_tag f, :summary %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/language_web/templates/word_list/index.html.eex
<h2>Current Vocab</h2>

<%= if @word_lists do %>
  <%= for word_list <- @word_lists do %>
    <%= render "show.html", Map.put(assigns, :word_list, word_list) %>
  <% end %>
<% end %>

<span><%= link "New Word List", to: word_list_path(@conn, :new) %></span>

lib/language_web/templates/word_list/new.html.eex
<h2>New Word List</h2>

<%= render "form.html", Map.put(assigns, :action, word_list_path(@conn, :create)) %>

<span><%= link "Back", to: word_list_path(@conn, :index) %></span>

lib/language_web/templates/word_list/show.html.eex
<div class="word_list">

  <h3><%= link @word_list.title, to: word_list_path(@conn, :show, @word_list)%>

  <td class="text-right">
    <span><%= link "Edit", to: word_list_path(@conn, :edit, @word_list), class: "btn btn-default btn-xs" %></span>
    <span><%= link "Delete", to: word_list_path(@conn, :delete, @word_list), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
  </td>

</h3>

  <span id="summary"><%= @word_list.summary %>

  <h4>Words</h4>

  <table class="words_table">
    <thead>
      <tr>
        <th>Original</th>
        <th>Replacement</th>
        <th>Notes</th>
        <th></th>
      </tr>
    </thead>

    </tr>

    <tbody>
      <%= for word <- @word_list.words do %>
        <tr>
          <td><%= word.native %></td>
          <td><%= word.replacement %></td>
          <td><%= word.notes %></td>

          <td class="text-right">
            <span><%= link "Show", to: word_path(@conn, :show, word), class: "btn btn-default btn-xs" %></span>
            <span><%= link "Edit", to: word_path(@conn, :edit, word), class: "btn btn-default btn-xs" %></span>
            <span><%= link "Delete", to: word_path(@conn, :delete, word), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
          </td>

        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link "Add Word", to: word_path(@conn, :new, word_list: @word_list.id), class: "btn btn-default btn-s" %>

</div>